---
 
weapons:
  - id: lightning
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      air: 1
    tagDamage:
      archer: 0.85
      soldier: 0.85
      villager: 1.0
      spearman: 0.75
      dog: 0.8
      wagon: 0.55
      knight: 0.30
      trebuchet: 0.45
      ballista: 0.30
      witch: 1.2           # from 1.3
      warship: 0.15
      travelboat: 0.20
      dragon: 0.8
      merman: 0.55
      mage: 0.35
      turtle: 0.2
      harpy: 1.3           # from 1.4
      structure: 0.35
      balloon: 1.0
      giant: 0.20
      commander: 0.2
      thief: 0.85
      rifleman: 0.95

...
