---

weapons:
  - id: trebuchetSling
    rangeMin: 4 # from 2
    rangeMax: 5
    canMoveAndAttack: false
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.2
      soldier: 1
      villager: 1
      spearman: 0.8
      dog: 1.1
      wagon: 0.7
      knight: 0.8
      trebuchet: 0.8
      ballista: 0.85
      mage: 0.9
      structure: 0.7 #from .85
      giant: 0.55
      commander: 0.25
      warship: 0.75
      harpoonship: 0.65
      turtle: 0.45
      travelboat: 0.8
      merman: 1

...
