---

weapons:
  - id: warshipCannon
    rangeMin: 2
    rangeMax: 3  # from 4
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.2
      soldier: 1.0
      villager: 1.0
      spearman: 0.75
      dog: 1.1
      wagon: 0.6
      knight: 0.7
      trebuchet: 0.8
      ballista: 0.85
      mage: 0.8
      structure: 0.75
      giant: 0.55
      commander: 0.25
      rifleman: 1.1
      thief: 1.0

      warship: 0.55
      turtle: 0.3
      harpoonship: 0.8
      merman: 0.75
      travelboat: 0.65

...
