---

grooves:
  - id: drain_aura
    name: groove_name_drain_aura
    description: groove_description_drain_aura
    maxCharge: 150
    chargePerUse: 150
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_drain_aura                    #   The verb associated with the groove. This should match the id of the verb in verbs.yaml.

  - id: second_wind
    name: groove_name_second_wind
    description: groove_description_second_wind
    maxCharge: 200
    chargePerUse: 200
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_second_wind  

  - id: convert   #elodie
    name: groove_name_convert
    description: groove_description_convert
    maxCharge: 150
    chargePerUse: 150
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_convert

  - id: dual_bombs   #twins will use fire first, then get water for free
    name: groove_name_dual_bombs
    description: groove_description_dual_bombs
    maxCharge: 150
    chargePerUse: 150
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_area_damage

  - id: area_heal   #twins will use fire first, then get water for free
    name: groove_name_dual_bombs
    description: groove_description_dual_bombs
    maxCharge: 1
    chargePerUse: 1
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_area_heal

  - id: diplomacy   # giving this to Mercival
    name: groove_name_diplomacy
    description: groove_description_diplomacy
    maxCharge: 150
    chargePerUse: 150
    chargeBy:
      endOfTurn: 10
      attack: 20
      counter: 10
      kill: 30
    verb: groove_diplomacy
...